#!/bin/bash

# exit on first non-true return value
set -o errexit
# exit if a command in a pipeline fails
set -o pipefail

echo 'Upgrading pyenv to latest'
cd /home/ubuntu/.pyenv/ && git pull && cd -

# go back home
cd "$(dirname "$0")/.."

VERSION=$(cat ./runtime.txt | sed 's/python-//')

echo "Installing Python v$VERSION"
pyenv install --skip-existing $VERSION

pyenv local $VERSION
